/* ==========================================================
                DEPARTMENTS
                USER MODULE
========================================================== */


/*
|--------------------------------------------------------------------------
| MOCK DATA
|--------------------------------------------------------------------------
| departmentData is generated by departments.php.
|--------------------------------------------------------------------------
*/


/* ==========================================================
                HOSPITAL NAME ROTATION
========================================================== */

const hospitalNames = [

    "City Care Hospital",

    "सिटी केयर हॉस्पिटल",

    "সিটি কেয়ার হাসপাতাল"

];

let hospitalNameIndex = 0;


const hospitalNameElement =
    document.getElementById("hospitalName");


if (hospitalNameElement) {

    setInterval(function () {

        hospitalNameElement.style.opacity = "0";


        setTimeout(function () {

            hospitalNameIndex++;


            if (
                hospitalNameIndex >=
                hospitalNames.length
            ) {

                hospitalNameIndex = 0;

            }


            hospitalNameElement.textContent =
                hospitalNames[hospitalNameIndex];


            hospitalNameElement.style.opacity = "1";

        }, 300);

    }, 2500);

}



/* ==========================================================
                DEPARTMENT MODAL
========================================================== */

const departmentModal =
    document.getElementById("departmentModal");


const closeDepartmentModal =
    document.getElementById("closeDepartmentModal");


const modalDepartmentIcon =
    document.getElementById("modalDepartmentIcon");


const modalDepartmentName =
    document.getElementById("modalDepartmentName");


const modalDepartmentDescription =
    document.getElementById(
        "modalDepartmentDescription"
    );


const modalDepartmentServices =
    document.getElementById(
        "modalDepartmentServices"
    );



/* ==========================================================
                OPEN MODAL
========================================================== */

function openDepartmentModal(department) {

    if (!departmentModal) {
        return;
    }


    modalDepartmentIcon.textContent =
        department.icon;


    modalDepartmentName.textContent =
        department.name;


    modalDepartmentDescription.textContent =
        department.description;


    modalDepartmentServices.innerHTML = "";


    department.services.forEach(function (service) {

        const li =
            document.createElement("li");

        li.textContent = service;

        modalDepartmentServices.appendChild(li);

    });


    departmentModal.classList.add("active");

}



/* ==========================================================
                CARD BUTTONS
========================================================== */

document
    .querySelectorAll(".department-card")
    .forEach(function (card) {


        const button =
            card.querySelector(".view-details-btn");


        if (!button) {
            return;
        }


        button.addEventListener(
            "click",
            function (event) {

                event.preventDefault();

                event.stopPropagation();


                const departmentId =
                    Number(card.dataset.departmentId);


                const department =
                    departmentData.find(
                        function (item) {

                            return Number(item.id) ===
                                departmentId;

                        }
                    );


                if (department) {

                    openDepartmentModal(
                        department
                    );

                }

            }
        );

    });



/* ==========================================================
                CLOSE MODAL
========================================================== */

if (closeDepartmentModal) {

    closeDepartmentModal.addEventListener(
        "click",
        function () {

            departmentModal.classList.remove(
                "active"
            );

        }
    );

}



/* ==========================================================
                CLOSE ON BACKGROUND CLICK
========================================================== */

if (departmentModal) {

    departmentModal.addEventListener(
        "click",
        function (event) {

            if (
                event.target ===
                departmentModal
            ) {

                departmentModal.classList.remove(
                    "active"
                );

            }

        }
    );

}



/* ==========================================================
                CLOSE WITH ESC
========================================================== */

document.addEventListener(
    "keydown",
    function (event) {

        if (
            event.key === "Escape" &&
            departmentModal
        ) {

            departmentModal.classList.remove(
                "active"
            );

        }

    }
);